title: Dust's Blog
description: Dust's blog
lang: en
google_analytics: G-N2PVPNWG20
remote_theme: chrisrhymes/bulma-clean-theme

# pagination settings
paginate: 5
paginate_path: /blog/page:num

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Dust Lee"
      layout: post
      # hero_image: /path/to/hero-image.jpg
      show_sidebar: true